spring:
  application:
    name: user-service

  threads:
    virtual:
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5433/veendibazaar_customer_db?TimeZone=Asia/Kolkata
    username: admin
    password: darga@786
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata

  kafka:
    bootstrap-servers: localhost:9092

    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest

      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

      properties:
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.shawbindro.userservice.user.event.dto.UserCreatedEvent

    listener:
      missing-topics-fatal: false

logging:
  level:
    root: INFO

    org.springframework.kafka: DEBUG
    org.springframework.kafka.listener: DEBUG

    org.apache.kafka.clients.consumer: INFO
    org.apache.kafka: DEBUG

    com.shawbindro.userservice.user: DEBUG

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000

      refresh-token:
        expiration: 604800000

server:
  servlet:
    context-path: /api/v1

  port: 8082