spring:
  application:
    name: User Service

  threads:
    virtual:
      enabled: true

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userdb?TimeZone=Asia/Kolkata
#    username: admin
#    password: darga@786
#    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password: admin

    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update   # use update / validate / none in prod
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: Asia/Kolkata
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    root: INFO
    com.shawbindro.userservice.user.controllers: DEBUG


